kind: Service
apiVersion: v1
metadata:
  name: kz-pharmacy-webapi
spec:
  selector:
    pod: kz-pharmacy-webapi-label
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: webapi-port