/*
 * Pharmacy Prescription API
 *
 * Pharmacy Prescription management system
 *
 * API version: 1.0.0
 * Contact: xkabac@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package pharmacy_pl

import (
	//  "net/http"

	"github.com/gin-gonic/gin"
)

type AmbulancesAPI interface {

	// internal registration of api routes
	addRoutes(routerGroup *gin.RouterGroup)

	// CreateAmbulance - Creates a new ambulance
	CreateAmbulance(ctx *gin.Context)

	// DeleteAmbulance - Deletes a specific ambulance
	DeleteAmbulance(ctx *gin.Context)
}

// partial implementation of AmbulancesAPI - all functions must be implemented in add on files
type implAmbulancesAPI struct {
}

func newAmbulancesAPI() AmbulancesAPI {
	return &implAmbulancesAPI{}
}

func (api *implAmbulancesAPI) addRoutes(routerGroup *gin.RouterGroup) {
	ambulanceGroup := routerGroup.Group("/ambulances")
	ambulanceGroup.POST("", api.CreateAmbulance)
	ambulanceGroup.DELETE("/:ambulanceId", api.DeleteAmbulance)
}

// Copy following section to separate file, uncomment, and implement accordingly
