/*
 * Pharmacy Prescription API
 *
 * Pharmacy Prescription management system
 *
 * API version: 1.0.0
 * Contact: xkabac@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

 package pharmacy_pl

import (
   "net/http"

   "github.com/gin-gonic/gin"
)

type MedicineOrdersAPI interface {

   // internal registration of api routes
   addRoutes(routerGroup *gin.RouterGroup)

    // CreateMedicineOrder - Creates a new medicine order
   CreateMedicineOrder(ctx *gin.Context)

    // DeleteMedicineOrder - Deletes a specific medicine order
   DeleteMedicineOrder(ctx *gin.Context)

    // GetAllMedicineOrders - Retrieves all medicine orders for an ambulance
   GetAllMedicineOrders(ctx *gin.Context)

    // GetMedicineOrderById - Retrieves a specific medicine order by ID
   GetMedicineOrderById(ctx *gin.Context)

    // UpdateMedicineOrder - Updates a specific medicine order
   UpdateMedicineOrder(ctx *gin.Context)

 }

 // partial implementation of MedicineOrdersAPI - all functions must be implemented in add on files
type implMedicineOrdersAPI struct {

}

func newMedicineOrdersAPI() MedicineOrdersAPI {
  return &implMedicineOrdersAPI{}
}

func (this *implMedicineOrdersAPI) addRoutes(routerGroup *gin.RouterGroup) {
  routerGroup.Handle( http.MethodPost, "/ambulances/:ambulanceId/medicineOrders", this.CreateMedicineOrder)
  routerGroup.Handle( http.MethodDelete, "/ambulances/:ambulanceId/medicineOrders/:orderId", this.DeleteMedicineOrder)
  routerGroup.Handle( http.MethodGet, "/ambulances/:ambulanceId/medicineOrders", this.GetAllMedicineOrders)
  routerGroup.Handle( http.MethodGet, "/ambulances/:ambulanceId/medicineOrders/:orderId", this.GetMedicineOrderById)
  routerGroup.Handle( http.MethodPut, "/ambulances/:ambulanceId/medicineOrders/:orderId", this.UpdateMedicineOrder)
}

// Copy following section to separate file, uncomment, and implement accordingly
// // CreateMedicineOrder - Creates a new medicine order
// func (this *implMedicineOrdersAPI) CreateMedicineOrder(ctx *gin.Context) {
//  	ctx.AbortWithStatus(http.StatusNotImplemented)
// }
//
// // DeleteMedicineOrder - Deletes a specific medicine order
// func (this *implMedicineOrdersAPI) DeleteMedicineOrder(ctx *gin.Context) {
//  	ctx.AbortWithStatus(http.StatusNotImplemented)
// }
//
// // GetAllMedicineOrders - Retrieves all medicine orders for an ambulance
// func (this *implMedicineOrdersAPI) GetAllMedicineOrders(ctx *gin.Context) {
//  	ctx.AbortWithStatus(http.StatusNotImplemented)
// }
//
// // GetMedicineOrderById - Retrieves a specific medicine order by ID
// func (this *implMedicineOrdersAPI) GetMedicineOrderById(ctx *gin.Context) {
//  	ctx.AbortWithStatus(http.StatusNotImplemented)
// }
//
// // UpdateMedicineOrder - Updates a specific medicine order
// func (this *implMedicineOrdersAPI) UpdateMedicineOrder(ctx *gin.Context) {
//  	ctx.AbortWithStatus(http.StatusNotImplemented)
// }
//

