/*
 * Pharmacy Prescription API
 *
 * Pharmacy Prescription management system
 *
 * API version: 1.0.0
 * Contact: xkabac@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package pharmacy_pl

import (
	"time"
)

type Prescription struct {

	Id string `json:"id"`

	PatientName string `json:"patientName"`

	PatientId string `json:"patientId"`

	DoctorName string `json:"doctorName"`

	IssuedDate time.Time `json:"issuedDate"`

	ValidUntil time.Time `json:"validUntil"`

	Medicines []Medicine `json:"medicines"`

	Status string `json:"status"`

	Instructions string `json:"instructions,omitempty"`

	Notes string `json:"notes,omitempty"`
}
