/*
 * Pharmacy Prescription API
 *
 * Pharmacy Prescription management system
 *
 * API version: 1.0.0
 * Contact: xkabac@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package pharmacy_pl

type Medicine struct {

	MedicineId string `json:"medicineId"`

	Name string `json:"name"`

	Dosage string `json:"dosage"`

	QuantityPrescribed int32 `json:"quantityPrescribed"`

	QuantityDispensed int32 `json:"quantityDispensed"`

	DispenseDate string `json:"dispenseDate"`

	Notes string `json:"notes,omitempty"`

	Unit string `json:"unit,omitempty"`
}
