/*
 * Pharmacy Prescription API
 *
 * Pharmacy Prescription management system
 *
 * API version: 1.0.0
 * Contact: xkabac@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package pharmacy_pl

type Prescription struct {

	Id string `json:"id"`

	PatientName string `json:"patientName"`

	DoctorName string `json:"doctorName"`

	IssuedDate string `json:"issuedDate"`

	ValidUntil string `json:"validUntil"`

	Medicines []Medicine `json:"medicines"`

	Status string `json:"status"`

	Instructions string `json:"instructions,omitempty"`

	AmbulanceId string `json:"ambulanceId"`

	Notes string `json:"notes,omitempty"`
}
