openapi: 3.0.0
servers:
  - description: Cluster Endpoint
    url: /api
info:
  description: Pharmacy Prescription management system
  version: "1.0.0"
  title: Pharmacy Prescription API
  contact:
    email: xkabac@stuba.sk
  license:
    name: CC BY 4.0
    url: "https://creativecommons.org/licenses/by/4.0/"
tags:
  - name: prescriptions
    description: Pharmacy Prescription API
  - name: ambulances
    description: Ambulance details
paths:
  "/ambulances":
    post:
      tags:
        - ambulances
      summary: Creates a new ambulance
      operationId: createAmbulance
      description: Use this endpoint to register a new ambulance in the system.
      requestBody:
        description: The ambulance data to register.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Ambulance'
      responses:
        "201":
          description: Ambulance created successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ambulance'
        "400":
          description: Invalid input provided.
        "409": 
          description: Ambulance with provided id already exists.

  "/ambulances/{ambulanceId}":
    delete:
      tags:
        - ambulances
      summary: Deletes a specific ambulance
      operationId: deleteAmbulance
      description: Use this endpoint to delete a specific ambulance by its ID.
      parameters:
        - in: path
          name: ambulanceId
          description: The ID of the ambulance to delete.
          required: true
          schema:
            type: string
      responses:
        "204":
          description: Ambulance deleted successfully.
        "404":
          description: Ambulance with the provided ID does not exist.
  "/prescriptions/{ambulanceId}":
    get:
      tags:
        - prescriptions
      summary: Provides the list of prescriptions for an ambulance
      operationId: getAmbulancePrescriptions
      description: By using ambulanceId, you get the list of prescriptions issued by the ambulance
      parameters:
        - in: path
          name: ambulanceId
          description: Pass the ID of the particular ambulance
          required: true
          schema:
            type: string
      responses:
        "200":
          description: A list of prescriptions for the ambulance
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Prescription"
        "404":
          description: Ambulance with such ID does not exist
    post:
      tags:
        - prescriptions
      summary: Creates a new prescription
      operationId: createPrescription
      description: Use this endpoint to create a new prescription associated with an ambulance.
      parameters:
        - in: path
          name: ambulanceId
          description: The ID of the ambulance where the prescription was issued.
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Prescription"
        description: The prescription to create.
        required: true
      responses:
        "201":
          description: Prescription created successfully.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Prescription"
        "400":
          description: Invalid input provided.
        "404":
          description: Ambulance with the provided ID does not exist.

  "/ambulances/{ambulanceId}/prescriptions/{prescriptionId}":
    get:
      tags:
        - prescriptions
      summary: Retrieves a specific prescription by ID
      operationId: getPrescriptionById
      description: Use this endpoint to retrieve details of a specific prescription by its ID and ambulanceId.
      parameters:
        - in: path
          name: ambulanceId
          description: The ID of the ambulance associated with the prescription.
          required: true
          schema:
            type: string
        - in: path
          name: prescriptionId
          description: The ID of the prescription to retrieve.
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Prescription retrieved successfully.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Prescription"
        "404":
          description: Prescription or ambulance with the provided ID does not exist.

    put:
      tags:
        - prescriptions
      summary: Updates a specific prescription
      operationId: updatePrescription
      description: Use this endpoint to update details of a specific prescription.
      parameters:
        - in: path
          name: ambulanceId
          description: The ID of the ambulance associated with the prescription.
          required: true
          schema:
            type: string
        - in: path
          name: prescriptionId
          description: The ID of the prescription to update.
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Prescription"
        description: The updated prescription details.
        required: true
      responses:
        "200":
          description: Prescription updated successfully.
        "400":
          description: Invalid input provided.
        "404":
          description: Prescription or ambulance with the provided ID does not exist.

    delete:
      tags:
        - prescriptions
      summary: Deletes a specific prescription
      operationId: deletePrescription
      description: Use this endpoint to delete a specific prescription by its ID.
      parameters:
        - in: path
          name: ambulanceId
          description: The ID of the ambulance associated with the prescription to delete.
          required: true
          schema:
            type: string
        - in: path
          name: prescriptionId
          description: The ID of the prescription to delete.
          required: true
          schema:
            type: string
      responses:
        "204":
          description: Prescription deleted successfully.
        "404":
          description: Prescription or ambulance with the provided ID does not exist.


components:
  schemas:
    Prescription:
      type: object
      required: [id, patientName, doctorName, issuedDate, validUntil, medicines, status, ambulanceId]
      properties:
        id:
          type: string
          example: RX123456789
        patientName:
          type: string
          example: John Smith
        doctorName:
          type: string
          example: Dr. Dutoschwarz
        issuedDate:
          type: string
          format: date-time
          example: "2038-12-24T10:35:00Z"
        validUntil:
          type: string
          format: date-time
          example: "2038-12-24T10:35:00Z"
        medicines:
          type: array
          items:
            $ref: '#/components/schemas/Medicine'
        status:
          type: string
          example: partially dispensed
        instructions:
          type: string
          example: Take one tablet three times a day after meals.
        ambulanceId:
          type: string
          example: "AMB123456789"
        notes:
          type: string
          example: Patient allergic to penicillin. Adjusted medication accordingly.

    Ambulance:
      type: object
      required: ["id", "name"]
      properties:
        id:
          type: string
          example: ambulance-petrzalka
          description: Unique identifier for the ambulance
        name: 
          type: string
          example: Ambulancia Dr. House, Petrzalka
          description: Human readable display name of the ambulance
        prescriptionList:
          type: array
          items:
            $ref: '#/components/schemas/Prescription'
      example: 
        $ref: '#components/examples/AmbulanceExample'
    Medicine:
      type: object
      required: [medicineId, name, dosage, quantityPrescribed, quantityDispensed, dispenseDate]
      properties:
        medicineId:
          type: string
          example: MED3001
        name:
          type: string
          example: Amoxicillin
        dosage:
          type: string
          example: 500mg
        quantityPrescribed:
          type: integer
          example: 30
        quantityDispensed:
          type: integer
          example: 30
        dispenseDate:
          type: string
          format: date
          example: "2024-04-02"
        notes:
          type: string
          example: Take 2 times a day with food to avoid stomach upset.
        unit:
          type: string
          example: tablets
  examples:
    AmbulanceExample:
      summary: Sample GP ambulance
      description: |
        Example of GP ambulance with waiting list and predefined conditions.
      value: 
        id: gp-house
        name: "Ambulancia vseobecneho lekarstva Dr. House"
        prescriptionList:
          - id: RX123456789
            patientName: John Smith
            doctorName: Dr. House
            issuedDate: "2024-04-01"
            validUntil: "2024-06-01"
            medicines:
              - medicineId: MED3001
                name: Amoxicillin
                dosage: "500mg"
                quantityPrescribed: 30
                quantityDispensed: 15
                dispenseDate: "2038-12-24T10:35:00Z"
                notes: "Take 2 times a day with food to avoid stomach upset."
                unit: tablets
            status: "partially dispensed"
            instructions: "Take one tablet three times a day after meals."
            ambulanceId: "gp-house"
            notes: "Patient allergic to penicillin. Adjusted medication accordingly."
          - id: RX987654321
            patientName: Alice Johnson
            doctorName: Dr. House
            issuedDate: "2038-12-24T10:35:00Z"
            validUntil: "2038-12-24T10:35:00Z"
            medicines:
              - medicineId: MED4002
                name: Ibuprofen
                dosage: "200mg"
                quantityPrescribed: 50
                quantityDispensed: 50
                dispenseDate: "2024-04-16"
                notes: "Take with food. Do not exceed 6 tablets per day."
                unit: tablets
            status: "dispensed"
            instructions: "Take two tablets twice a day."
            ambulanceId: "gp-house"
            notes: "Check blood pressure regularly while on medication."